export default [
  "Panasonic 34l Microwave",
  "40cm Pedestal Fan",
  "Salton 15kg Ice Maker",
  "Samsung Galaxy J5 Prime Gold",
  "Casio Cash Register",
  "Weber 47cm Compact Kettle Braai",
  "Terrace Leisure Box Patio Set",
  "Defy Chest Freezer",
  "Pallet of beer",
  "Panasonic 34l Microwave",
  "40cm Pedestal Fan",
  "Salton 15kg Ice Maker",
  "Samsung Galaxy J5 Prime Gold",
  "Casio Cash Register",
  "Weber 47cm Compact Kettle Braai",
  "Terrace Leisure Box Patio Set",
  "Defy Chest Freezer",
  "Pallet of beer"
];
